# SPRING CONFIG
spring:
  application:
    name: FTC.UserManager.API
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5453/ftc_user_manager_database
    username: postgres
    password: postgres
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      FAIL_ON_EMPTY_BEANS: false
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
    time-zone: America/Sao_Paulo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    mandatory-file-encoding: UTF-8
    profiles:
      active: local
  devtools:
    livereload:
      enabled: false
  flyway:
    schemas: public
    table: t_flyway_schema_history
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration