server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8085
  servlet:
    context-path: /restaurant-manager
    encoding:
      charset: UTF-8
      enabled: true

spring:
  application:
    name: FTC.RestaurantManager.API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ftc_restaurant_manager_database:5432/ftc_restaurant_manager_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: broker:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      name:
        order-topic: orders
        reservation-topic: reservations
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      FAIL_ON_EMPTY_BEANS: false
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
    time-zone: America/Sao_Paulo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    schemas: public
    table: t_flyway_schema_history
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    org:
      springframework.web: DEBUG
      org.hibernate: ERROR
