# SERVER CONFIG
server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8085
  servlet:
    context-path: /restaurant-manager
    encoding:
      charset: UTF-8
      enabled: true

# SPRING CONFIG
spring:
  application:
    name: FTC.RestaurantManager.API
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5453/ftc_restaurant_manager_database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name:
        producer: dto
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      FAIL_ON_EMPTY_BEANS: false
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
    time-zone: America/Sao_Paulo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
  devtools:
    livereload:
      enabled: false
  mandatory-file-encoding: UTF-8
  flyway:
    schemas: public
    table: t_flyway_schema_history
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: user
logging:
  level:
    org:
      flywaydb: debug
      springframework.web: DEBUG
      org.hibernate: ERROR

# SECURITY
security:
  jwt:
    expiration-in-milliseconds: 3600000 #one hour
    tokens:
      bearer-token-secret-key: cyy4KhQAOWuj94LtM6Yvt$FGOQb8KBN6lIXmFFG7!Yv6K#ewWCnH#Q5IS2MhxKp&
      bearer-token-validity-in-milliseconds: 3600000

#CRYPTO
crypto:
  key: 5E50F405ACE6CBDF17379F4B9F2B0C9F4144C5E380EA0B9298CB02EBD8FFE511

#SWAGGER (URL: http://localhost:8085/restaurant-manager/swagger-ui/index.html)
server.swagger.base.url: http://localhost:8085/restaurant-manager
springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
  writer-with-order-by-keys: true