# SERVER CONFIG
server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: 8084
  servlet:
    context-path: /user-manager
  header-ip-candidates: X-Forwarded-For,Proxy-Client-IP,WL-Proxy-Client-IP,HTTP_X_FORWARDED_FOR,HTTP_X_FORWARDED,HTTP_X_CLUSTER_CLIENT_IP,HTTP_CLIENT_IP,HTTP_FORWARDED_FOR,HTTP_FORWARDED,HTTP_VIA,REMOTE_ADDR

# SPRING CONFIG
spring:
  application:
    name: FTC.UserManager.API
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5453/ftc_user_manager_database
    username: postgres
    password: postgres
  http:
    encoding:
      charset: UTF-8
      enabled: true
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
      FAIL_ON_EMPTY_BEANS: false
    mapper:
      ALLOW_COERCION_OF_SCALARS: false
    time-zone: America/Sao_Paulo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
    mandatory-file-encoding: UTF-8
    profiles:
      active: local
  devtools:
    livereload:
      enabled: false
  flyway:
    schemas: public
    table: t_flyway_schema_history
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  security:
    user:
      name: user
      password: user

#SWAGGER (URL: http://localhost:8084/user-manager/swagger-ui)
server.swagger.base.url: http://localhost:8084/user-manager
springdoc.swagger-ui.operationsSorter: method
springdoc.swagger-ui.tagsSorter: alpha
springdoc.swagger-ui.defaultModelsExpandDepth: -1
springdoc:
  writer-with-order-by-keys: true